"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { httpsCallable, getFunctions } from "firebase/functions";
import { getFirebaseApp } from "@studiqa/firebase-config";

interface GenerateMindMapResponse {
  mapId: string;
}

export default function CreateMindMapPage() {
  const router = useRouter();
  const [topic, setTopic] = useState("");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function handleGenerate(e: React.FormEvent) {
    e.preventDefault();
    setLoading(true);
    setError(null);
    try {
      // This callable is protected by App Check + Firebase Auth + a server-side
      // usage-limit check (see functions/src/aiProxy/generateMindMap.ts) — the
      // client never talks to the AI provider directly with a real API key.
      const generateMindMap = httpsCallable<{ topic: string }, GenerateMindMapResponse>(
        getFunctions(getFirebaseApp()),
        "generateMindMap"
      );
      const result = await generateMindMap({ topic });
      router.push(`/mindmaps/${result.data.mapId}`);
    } catch (err: any) {
      // "resource-exhausted" is thrown by the function when the free-tier limit is hit.
      if (err?.code === "functions/resource-exhausted") {
        setError("You've reached your free mind-map limit this month. Upgrade for unlimited maps.");
      } else {
        setError("Something went wrong generating your mind map. Please try again.");
      }
    } finally {
      setLoading(false);
    }
  }

  return (
    <main style={{ padding: 48, maxWidth: 480, margin: "0 auto" }}>
      <h1>Create a mind map</h1>
      <p>Enter a topic (e.g. "Operating Systems — Deadlock") and Studiqa will generate an interactive map.</p>
      <form onSubmit={handleGenerate}>
        <input
          value={topic}
          onChange={(e) => setTopic(e.target.value)}
          placeholder="Topic name"
          required
          style={{ width: "100%", padding: 8 }}
        />
        <button type="submit" disabled={loading || topic.trim().length === 0} style={{ marginTop: 12 }}>
          {loading ? "Generating…" : "Generate mind map"}
        </button>
      </form>
      {error && <p role="alert" style={{ color: "crimson" }}>{error}</p>}
      <p style={{ fontSize: 12, opacity: 0.7, marginTop: 24 }}>Generated by AI — verify important facts.</p>
    </main>
  );
}
