"use client";
import { useEffect, useState } from "react";
import { doc, onSnapshot } from "firebase/firestore";
import { getAuth } from "firebase/auth";
import { getFirebaseApp, db } from "@studiqa/firebase-config";

interface NoteSection { heading: string; body: string; keyPoints: string[]; }
interface Note { id: string; title: string; sections: NoteSection[]; }

export default function NoteViewerPage({ params }: { params: { id: string } }) {
  const [note, setNote] = useState<Note | null>(null);

  useEffect(() => {
    const uid = getAuth(getFirebaseApp()).currentUser?.uid;
    if (!uid) return;
    return onSnapshot(doc(db(), "users", uid, "notes", params.id), (snap) => {
      if (snap.exists()) setNote({ id: snap.id, ...(snap.data() as Omit<Note, "id">) });
    });
  }, [params.id]);

  if (!note) return <main style={{ padding: 48 }}>Loading notes…</main>;

  return (
    <main style={{ padding: 48, maxWidth: 720, margin: "0 auto" }}>
      <h1>{note.title}</h1>
      {note.sections.map((s, i) => (
        <section key={i} style={{ marginBottom: 32 }}>
          <h2>{s.heading}</h2>
          <p>{s.body}</p>
          <ul>{s.keyPoints.map((k, j) => <li key={j}>{k}</li>)}</ul>
        </section>
      ))}
      <p style={{ fontSize: 12, opacity: 0.7 }}>Generated by AI — verify important facts.</p>
    </main>
  );
}
